# Generated by Django 5.0.6 on 2024-06-05 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ubishop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categoria',
            table='categoria',
        ),
        migrations.AlterModelTable(
            name='convenio',
            table='convenios',
        ),
        migrations.AlterModelTable(
            name='detallereserva',
            table='detalles_reserva',
        ),
        migrations.AlterModelTable(
            name='inventario',
            table='inventario',
        ),
        migrations.AlterModelTable(
            name='perfil',
            table='perfil',
        ),
        migrations.AlterModelTable(
            name='producto',
            table='productos',
        ),
        migrations.AlterModelTable(
            name='productocategoria',
            table='producto_categoria',
        ),
        migrations.AlterModelTable(
            name='resena',
            table='resenas',
        ),
        migrations.AlterModelTable(
            name='reserva',
            table='reservas',
        ),
        migrations.AlterModelTable(
            name='rol',
            table='roles',
        ),
        migrations.AlterModelTable(
            name='tienda',
            table='tiendas',
        ),
        migrations.AlterModelTable(
            name='ubicacion',
            table='ubicacion',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios',
        ),
        migrations.DeleteModel(
            name='Oferta',
        ),
    ]
