# Generated by Django 5.0.6 on 2024-06-12 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ubishop', '0002_alter_categoria_table_alter_convenio_table_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto',
            new_name='Productos',
        ),
    ]
